export const Dummydata = [
  {
    userId: 44,
    firstName: "Varun",
    lastName: "Sharma",
    email: "varun.sharma@cginfinity.com",
    durationOfInternship: 10,
    internId: "INT420",
    isDeployed: false,
    skills: {
      Salesforce: "Beginner",
      JavaScript: "Intermediate",
      Angular: "Beginner",
      React: "Beginner",
    },
    beginnerCount: 2,
    intermediateCount: 2,
    advanceCount: 2,
  },
  {
    userId: 45,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    durationOfInternship: 8,
    internId: "INT123",
    isDeployed: true,
    skills: {
      Java: "Intermediate",
      Python: "Advanced",
      SQL: "Beginner",
      HTML: "Intermediate",
    },
    beginnerCount: 1,
    intermediateCount: 3,
    advanceCount: 1,
  },
  {
    userId: 46,
    firstName: "Alice",
    lastName: "Smith",
    email: "alice.smith@example.com",
    durationOfInternship: 12,
    internId: "INT789",
    isDeployed: false,
    skills: {
      "C++": "Intermediate",
      JavaScript: "Advanced",
      React: "Intermediate",
      "Node.js": "Beginner",
    },
    beginnerCount: 1,
    intermediateCount: 2,
    advanceCount: 1,
  },
  {
    userId: 47,
    firstName: "Emma",
    lastName: "Johnson",
    email: "emma.johnson@example.com",
    durationOfInternship: 6,
    internId: "INT567",
    isDeployed: true,
    skills: {
      Python: "Beginner",
      HTML: "Intermediate",
      CSS: "Intermediate",
      Django: "Beginner",
    },
    beginnerCount: 2,
    intermediateCount: 2,
    advanceCount: 0,
  },
  {
    userId: 48,
    firstName: "David",
    lastName: "Williams",
    email: "david.williams@example.com",
    durationOfInternship: 9,
    internId: "INT246",
    isDeployed: false,
    skills: {
      Ruby: "Beginner",
      JavaScript: "Intermediate",
      Rails: "Beginner",
      HTML: "Intermediate",
    },
    beginnerCount: 1,
    intermediateCount: 2,
    advanceCount: 1,
  },
  {
    userId: 49,
    firstName: "Sophia",
    lastName: "Brown",
    email: "sophia.brown@example.com",
    durationOfInternship: 7,
    internId: "INT678",
    isDeployed: true,
    skills: {
      "C#": "Beginner",
      "ASP.NET": "Intermediate",
      SQL: "Intermediate",
      HTML: "Beginner",
    },
    beginnerCount: 2,
    intermediateCount: 1,
    advanceCount: 0,
  },
  {
    userId: 50,
    firstName: "Oliver",
    lastName: "Taylor",
    email: "oliver.taylor@example.com",
    durationOfInternship: 11,
    internId: "INT135",
    isDeployed: false,
    skills: {
      PHP: "Intermediate",
      JavaScript: "Advanced",
      Laravel: "Intermediate",
      HTML: "Beginner",
    },
    beginnerCount: 1,
    intermediateCount: 3,
    advanceCount: 2,
  },
  {
    userId: 51,
    firstName: "Isabella",
    lastName: "Martinez",
    email: "isabella.martinez@example.com",
    durationOfInternship: 8,
    internId: "INT789",
    isDeployed: true,
    skills: {
      Java: "Beginner",
      Python: "Intermediate",
      "Spring Boot": "Intermediate",
      HTML: "Beginner",
    },
    beginnerCount: 2,
    intermediateCount: 2,
    advanceCount: 1,
  },
  {
    userId: 52,
    firstName: "Mia",
    lastName: "Anderson",
    email: "mia.anderson@example.com",
    durationOfInternship: 9,
    internId: "INT246",
    isDeployed: false,
    skills: {
      JavaScript: "Intermediate",
      React: "Intermediate",
      "Node.js": "Beginner",
      CSS: "Intermediate",
    },
    beginnerCount: 1,
    intermediateCount: 3,
    advanceCount: 0,
  },
  {
    userId: 53,
    firstName: "Alexander",
    lastName: "Hernandez",
    email: "alexander.hernandez@example.com",
    durationOfInternship: 7,
    internId: "INT678",
    isDeployed: true,
    skills: {
      Python: "Beginner",
      Django: "Intermediate",
      HTML: "Intermediate",
      CSS: "Beginner",
    },
    beginnerCount: 2,
    intermediateCount: 2,
    advanceCount: 1,
  },
  {
    userId: 54,
    firstName: "Ava",
    lastName: "Garcia",
    email: "ava.garcia@example.com",
    durationOfInternship: 10,
    internId: "INT420",
    isDeployed: false,
    skills: {
      Salesforce: "Intermediate",
      JavaScript: "Intermediate",
      Angular: "Advanced",
      React: "Beginner",
    },
    beginnerCount: 1,
    intermediateCount: 2,
    advanceCount: 2,
  },
  {
    userId: 55,
    firstName: "James",
    lastName: "Lopez",
    email: "james.lopez@example.com",
    durationOfInternship: 8,
    internId: "INT123",
    isDeployed: true,
    skills: {
      Java: "Advanced",
      Python: "Intermediate",
      SQL: "Intermediate",
      HTML: "Beginner",
    },
    beginnerCount: 1,
    intermediateCount: 3,
    advanceCount: 1,
  },
  {
    userId: 56,
    firstName: "Charlotte",
    lastName: "Lee",
    email: "charlotte.lee@example.com",
    durationOfInternship: 12,
    internId: "INT789",
    isDeployed: false,
    skills: {
      "C++": "Intermediate",
      JavaScript: "Advanced",
      React: "Intermediate",
      "Node.js": "Beginner",
    },
    beginnerCount: 1,
    intermediateCount: 2,
    advanceCount: 1,
  },
  {
    userId: 57,
    firstName: "Liam",
    lastName: "Gonzalez",
    email: "liam.gonzalez@example.com",
    durationOfInternship: 6,
    internId: "INT567",
    isDeployed: true,
    skills: {
      Python: "Beginner",
      HTML: "Intermediate",
      CSS: "Intermediate",
      Django: "Beginner",
    },
    beginnerCount: 2,
    intermediateCount: 2,
    advanceCount: 0,
  },
  {
    userId: 58,
    firstName: "Benjamin",
    lastName: "Rodriguez",
    email: "benjamin.rodriguez@example.com",
    durationOfInternship: 9,
    internId: "INT246",
    isDeployed: false,
    skills: {
      Ruby: "Beginner",
      JavaScript: "Intermediate",
      Rails: "Beginner",
      HTML: "Intermediate",
    },
    beginnerCount: 1,
    intermediateCount: 2,
    advanceCount: 1,
  },
  {
    userId: 59,
    firstName: "Harper",
    lastName: "Lopez",
    email: "harper.lopez@example.com",
    durationOfInternship: 7,
    internId: "INT678",
    isDeployed: true,
    skills: {
      "C#": "Beginner",
      "ASP.NET": "Intermediate",
      SQL: "Intermediate",
      HTML: "Beginner",
    },
    beginnerCount: 2,
    intermediateCount: 1,
    advanceCount: 0,
  },
  {
    userId: 60,
    firstName: "Evelyn",
    lastName: "Reed",
    email: "evelyn.reed@example.com",
    durationOfInternship: 11,
    internId: "INT135",
    isDeployed: false,
    skills: {
      PHP: "Intermediate",
      JavaScript: "Advanced",
      Laravel: "Intermediate",
      HTML: "Beginner",
    },
    beginnerCount: 1,
    intermediateCount: 3,
    advanceCount: 2,
  },
];
